site_name: STK Files

nav:
  - File Types:
    - Attitude: attitude.md
    - Ephemeris: ephemeris.md
    - Interval: interval.md
    - Sensor Pointing: sensor.md
  - API: api.md

theme:
  name: "readthedocs"

plugins:
- mkdocstrings
